# -*- coding: utf-8 -*-
"""Art parameters."""
from .text_dic1 import *
from .decor_dic import *

ART_VERSION = "5.8"  # pragma: no cover
FONT_SMALL_THRESHOLD = 50  # pragma: no cover
FONT_MEDIUM_THRESHOLD = 100  # pragma: no cover
FONT_LARGE_THRESHOLD = 200  # pragma: no cover

TEXT_XLARGE_THRESHOLD = 3  # pragma: no cover
TEXT_LARGE_THRESHOLD = 7  # pragma: no cover
TEXT_MEDIUM_THRESHOLD = 10  # pragma: no cover

ART_TYPE_ERROR = "The 'artname' type must be str."
ART_NAME_ERROR = "Invalid art name."
NUMBER_TYPE_ERROR = "The 'number' type must be int."
TEXT_TYPE_ERROR = "The 'text' type must be str."
FONT_TYPE_ERROR = "The 'font' type must be str."
DECORATION_TYPE_ERROR = "The 'decoration' type must be str."
CHR_IGNORE_TYPE_ERROR = "The 'chr_ignore' type must be bool."
FILE_TYPE_ERROR = "The 'filename' type must be str."
PRINT_STATUS_TYPE_ERROR = "The 'print_status' type must be bool."
OVERWRITE_TYPE_ERROR = "The 'overwrite' type must be bool."
SEP_TYPE_ERROR = "The 'sep' type must be str."
ART_ENVIRONMENT_WARNING = "[Warning] '{0}' is not printable in this environment."
FONT_ENVIRONMENT_WARNING = "[Warning] '{0}' is not printable in this environment."
PACKAGE_LOAD_WARNING = "[Warning] There is a problem loading the package 'coverage'."

SMALL_WIZARD_FONT = [
    "contessa",
    "avatar",
    "mini",
    "bigfig",
    "lcd",
    "bubble",
    "digital",
    "twopoint",
    "3x5",
    "threepoint",
    "ascii_new_roman",
    "bulbhead",
    "lockergnome"]  # pragma: no cover
MEDIUM_WIZARD_FONT = [
    "soft",
    "4max",
    "5x7",
    "stampate",
    "o8",
    "standard",
    "alphabet",
    "computer",
    "shadow",
    "speed",
    "rounded",
    "chartri"]  # pragma: no cover
LARGE_WIZARD_FONT = [
    "xhelvi",
    "utopiai",
    "rev",
    "smpoison",
    "3-d",
    "larry3d",
    "nancyj",
    "nancyj-underlined",
    "os2",
    "block2"]  # pragma: no cover
XLARGE_WIZARD_FONT = [
    "dotmatrix",
    "univers",
    "doh",
    "roman",
    "hollywood",
    "georgia11",
    "block"]  # pragma: no cover

UPPERCASE_FONTS = [
    "1943",
    "4x4_offr",
    "64f1",
    "a_zooloo",
    "advenger",
    "aquaplan",
    "assalt_m",
    "asslt_m",
    "atc",
    "atc_gran",
    "battlesh",
    "baz_bil",
    "beer_pub",
    "c1",
    "c2",
    "c_consen",
    "char1",
    "char4",
    "coil_cop",
    "druid",
    "faces_of",
    "fair_mea",
    "fairligh",
    "fantasy1",
    "fbr1",
    "fbr12",
    "fbr_stri",
    "fbr_tilt",
    "finalass",
    "fp1",
    "fp2",
    "funky_dr",
    "future_1",
    "future_2",
    "future_3",
    "future_4",
    "future_5",
    "future_6",
    "future_7",
    "future_8",
    "ghost_bo",
    "grand_pr",
    "green_be",
    "hades",
    "heavy_me",
    "heroboti",
    "house_of",
    "hypa_bal",
    "hyper",
    "kgames_i",
    "kik_star",
    "krak_out",
    "tsn_base",
    "ugalympi",
    "unarmed",
    "usa",
    "usa_pq",
    "vortron",
    "war_of_w",
    "yie-ar",
    "yie_ar_k",
    "z-pilot",
    "zig_zag",
    "zone7"]

NON_ASCII_ARTS = [
    '3',
    '5',
    '9/11 truth',
    'acid',
    'afraid',
    'airplane1',
    'airplane2',
    'airplane3',
    'ak-47',
    'almost cared',
    'american money2',
    'american money3',
    'american money4',
    'american money5',
    'angry birds',
    'angry face',
    'angry face2',
    'angry troll',
    'angry',
    'angry2',
    'ankush',
    'arrow1',
    'arrowhead',
    'at what cost',
    'awkward',
    'band aid',
    'barbell',
    'barcode1',
    'barcode2',
    'barf',
    'basking in glory',
    'bautista',
    'bear GTFO',
    'bear squiting',
    'bear',
    'bear2',
    'because',
    'bee',
    'being draged',
    'bender',
    'big eyes',
    'big nose',
    'bird',
    'birds',
    'bomb',
    'boombox1',
    'boombox2',
    'boxing',
    'breakdown',
    'british money',
    'bullshit',
    'butt',
    'butterfly',
    'camera',
    'car race',
    'careless',
    'cassette1',
    'cassette2',
    'cat face',
    'cat smile',
    'cat2',
    'cat4',
    'catlenny',
    'chair',
    'chasing',
    'cheer',
    'cheers',
    'chess pieces',
    'chess',
    'chicken',
    'chu',
    'cigarette1',
    'club bold',
    'club regular',
    'coffee now',
    'confused scratch',
    'confused3',
    'confused5',
    'confused6',
    'confused7',
    'confused8',
    'confused9',
    'crayons',
    'crazy',
    'creeper',
    'cry face',
    'cry troll',
    'cry',
    'crying1',
    'cup1',
    'cup2',
    'cute cat',
    'cute face',
    'cute face2',
    'cute face3',
    'cute face4',
    'cute face5',
    'cute face6',
    'cute face7',
    'cute face8',
    'cute face9',
    'upset',
    'dab',
    'dalek',
    'damnyou',
    'dance2',
    'dancee',
    'dancing people',
    'dancing',
    'dead eyes',
    'dear god why',
    'decorate',
    'depressed',
    'derp',
    'devious smile',
    'dgaf',
    'diamond bold',
    'diamond regular',
    'disagree',
    'discombobulated',
    'dislike1',
    'dislike2',
    'do you even lift bro?',
    'double flip',
    'drowning',
    'drunkenness',
    'dunno',
    'dunno2',
    'dunno3',
    'dunno4',
    'dunno5',
    'electrocardiogram1',
    'electrocardiogram2',
    'electrocardiogram3',
    'electrocardiogram4',
    'elephant',
    'emo dance',
    'energy',
    'envelope',
    'epic gun',
    'equalizer',
    'error',
    'exchange',
    'excited',
    'exorcism',
    'eye closed',
    'eye roll',
    'eyes',
    'face',
    'facepalm',
    'fail',
    'fart',
    'feel perky',
    'fido',
    'fight',
    'finger1',
    'finger2',
    'finger3',
    'finger4',
    'finn',
    'fish invasion',
    'fish swim',
    'fish3',
    'fisticuffs',
    'flex',
    'flip friend',
    'fly away',
    'flying',
    'formula1 car',
    'french kiss',
    'frown',
    'fu',
    'fuck you2',
    'fuckall',
    'fungry',
    'ghost',
    'gimme',
    'glasses2',
    'glitter',
    'go away bear',
    'gotit',
    'gtalk fit',
    'guitar',
    'gun1',
    'gun2',
    'gun3',
    'gun4',
    'hairstyle',
    'happy birthday 1',
    'happy face',
    'happy hug',
    'happy square',
    'happy',
    'happy2',
    'happy3',
    'happy6',
    'happy7',
    'happy8',
    'happy9',
    'happy10',
    'happy11',
    'happy12',
    'happy13',
    'happy14',
    'happy15',
    'happy16',
    'happy17',
    'happy18',
    'happy19',
    'happy20',
    'happy21',
    'happy22',
    'happy23',
    'happy24',
    'happy25',
    'happy26',
    'happy27',
    'head shot',
    'heart bold',
    'heart regular',
    'heart1',
    'heart2',
    'hell yeah',
    'hello',
    'hello2',
    'help',
    'high five',
    'hitchhicking',
    'honeycute',
    'house',
    'hug me',
    'hugger',
    'huhu',
    'hybrix',
    'i dont care',
    'i kill you',
    'im a hugger',
    'injured',
    'inlove',
    'innocent face',
    'japanese lion face',
    'jaymz',
    'jazz musician',
    'john lennon',
    'joker1',
    'joker2',
    'joker3',
    'joker4',
    'jokeranonimous',
    'jokeranonimous2',
    'judgemental',
    'judging',
    'kablewee',
    'killer',
    'kilroy was here',
    'kirby',
    'kissing',
    'kissing2',
    'kissing3',
    'kissing4',
    'kissing5',
    'kissing6',
    'kiss2',
    'kiss3',
    'kitty emote',
    'kokain',
    'kyubey',
    'kyubey2',
    'laughing',
    'lenny',
    'line brack',
    'listening to headphones',
    'loading1',
    'loading2',
    'loading3',
    'loading4',
    'loading5',
    'loading6',
    'looking face',
    'love in my eye1',
    'love in my eye2',
    'love in my eye3',
    'love',
    'love2',
    'love3',
    'love4',
    'man spider',
    'spider4',
    'man tears',
    'mango',
    'med man',
    'med',
    'meditation',
    'meep',
    'meow',
    'monocle',
    'monster',
    'monster2',
    'mouse2',
    'mouse3',
    'mouse4',
    'myancat',
    'nathan',
    'needle1',
    'neo',
    'no support',
    'nose',
    'opera',
    'owlkin',
    'pac man',
    'panda',
    'party time',
    'peace yo!',
    'peepers',
    'penis2',
    'perky',
    'pig2',
    'piggy',
    'ping pong',
    'pirate',
    'pistols1',
    'pistols2',
    'pistols3',
    'pistols4',
    'pistols5',
    'mad',
    'mad2',
    'mad5',
    'mad6',
    'mad7',
    'mad9',
    'mad10',
    'playing cards clubs',
    'playing cards clubs waterfall',
    'playing cards diamonds',
    'playing cards diamonds waterfall',
    'playing cards hearts',
    'playing cards hearts waterfall',
    'playing cards spades',
    'playing cards spades waterfall',
    'playing cards',
    'playing cards waterfall',
    'playing cards waterfall (trump)',
    'playing in snow',
    'point',
    'polar bear',
    'pretty eyes',
    'professor',
    'puls',
    'put the table back',
    'rak',
    'rare',
    'real face',
    'religious',
    'resting my eyes',
    'robber',
    'robot boy',
    'robot2',
    'robot3',
    'rocket',
    'rope',
    'round bird',
    'running',
    'sad and confused',
    'sad and crying',
    'sad face',
    'sad1',
    'sad2',
    'sad3',
    'sad4',
    'sad5',
    'sat',
    'satan',
    'satisfied',
    'scissors',
    'seal',
    'sex symbol',
    'shark face',
    'sheep',
    'shocked1',
    'shrug',
    'shy',
    'singing',
    'singing2',
    'sky free',
    'sleepy coffee',
    'sleepy',
    'slenderman',
    'smooth',
    'smug bastard',
    'sniper rifle',
    'sniperstars',
    'snowing',
    'snowman1',
    'sorreh bro',
    'spade bold',
    'spade regular',
    'sparkling heart',
    'spell cast',
    'squee',
    'squid',
    'srs face',
    'staring',
    'stars',
    'stars2',
    'stranger danger',
    'strut',
    'stunna shades',
    'sunglasses1',
    'sunny day',
    'surprised2',
    "surprised4",
    "surprised5",
    "surprised6",
    "surprised8",
    "surprised9",
    "surprised10",
    "surprised11",
    "surprised12",
    "surprised13",
    "surprised15",
    "surprised16",
    "surprised17",
    "surprised18",
    "surprised19",
    "surprised20",
    'sword2',
    'sword3',
    'sword8',
    'sword9',
    'table flip',
    'table flip2',
    'table flip3',
    'table flip4',
    'table flip5',
    'table flip6',
    'table flip7',
    'table flip8',
    'table flip9',
    'table flip10',
    'taking a dump',
    'teddy',
    'telephone',
    'tgif',
    'things that can_t be unseen',
    'tidy up',
    'tie-fighter',
    'tired',
    'touchy feely',
    'toungue out1',
    'train',
    'tripping out',
    'trolling',
    'umadbro',
    'up',
    'upsidedown',
    'wat',
    'wat-wat',
    'waves',
    'weather',
    'what?',
    'what??',
    'whisling',
    'why',
    'winnie the pooh',
    'winning',
    'wizard',
    'wizard2',
    'woman',
    'worried',
    'wtf dude?',
    'yessir',
    'yolo',
    'yun',
    'zable',
    'zoidberg',
    'zombie',
    'zombie2',
    'zoned',
    'swim',
    'swim2',
    'swim3',
    'yawning',
    'boobs2']

RANDOM_FILTERED_ARTS = [] + NON_ASCII_ARTS


NON_ASCII_FONTS = [
    "contouring1",
    "contouring2",
    "contouring3",
    "contouring4",
    "mirror",
    "mirror_flip",
    "flip",
    "white_bubble",
    "smallcaps2",
    "superscript",
    "subscript1",
    "full_width",
    "antrophobia",
    "currency",
    "special",
    "dirty",
    "knight",
    "thin2",
    "tiny",
    "love1",
    "love2",
    "fancy1",
    "fancy2",
    "fancy3",
    "fancy4",
    "fancy5",
    "fancy6",
    "fancy7",
    "fancy8",
    "fancy9",
    "fancy10",
    "fancy11",
    "fancy12",
    "fancy13",
    "fancy14",
    "fancy15",
    "fancy16",
    "fancy17",
    "fancy18",
    "fancy19",
    "fancy20",
    "fancy21",
    "fancy22",
    "fancy23",
    "fancy24",
    "fancy25",
    "fancy26",
    "fancy27",
    "fancy28",
    "fancy29",
    "fancy30",
    "symbols",
    "fancy31",
    "fancy32",
    "fancy33",
    "fancy34",
    "fancy35",
    "fancy36",
    "fancy37",
    "fancy38",
    "fancy39",
    "fancy40",
    "fancy41",
    "fancy42",
    "fancy43",
    "fancy44",
    "fancy45",
    "fancy46",
    "fancy47",
    "fancy48",
    "fancy49",
    "fancy50",
    "fancy52",
    "fancy53",
    "fancy54",
    "fancy55",
    "fancy56",
    "fancy57",
    "fancy58",
    "fancy59",
    "fancy60",
    "fancy61",
    "fancy62",
    "fancy63",
    "fancy64",
    "fancy65",
    "fancy66",
    "fancy67",
    "fancy68",
    "fancy69",
    "fancy70",
    "fancy71",
    "fancy72",
    "fancy73",
    "fancy74",
    "fancy75",
    "fancy76",
    "fancy77",
    "fancy78",
    "fancy79",
    "fancy80",
    "fancy81",
    "fancy82",
    "fancy83",
    "fancy84",
    "fancy85",
    "fancy86",
    "fancy87",
    "fancy88",
    "fancy89",
    "fancy90",
    "fancy91",
    "fancy92",
    "fancy93",
    "fancy94",
    "fancy95",
    "fancy96",
    "fancy97",
    "fancy98",
    "fancy99",
    "fancy100",
    "fancy101",
    "fancy102",
    "fancy103",
    "fancy104",
    "fancy105",
    "fancy106",
    "fancy107",
    "fancy108",
    "fancy109",
    "fancy110",
    "fancy111",
    "fancy112",
    "fancy113",
    "fancy114",
    "fancy115",
    "fancy116",
    "fancy117",
    "fancy118",
    "fancy119",
    "fancy120",
    "fancy121",
    "fancy122",
    "fancy123",
    "fancy124",
    "fancy125",
    "fancy126",
    "fancy127",
    "fancy128",
    "fancy129",
    "fancy131",
    "fancy132",
    "fancy133",
    "fancy134",
    "fancy135",
    "fancy136",
    "fancy137",
    "fancy138",
    "fancy139",
    "fancy140",
    "fancy141",
    "fancy142",
    "fancy143",
    "fancy144",
    "fancy145",
    "fancy146",
    "fancy147",
    "fancy148",
    "foxy",
    "white_square",
    "black_square",
    "paranormal",
    "black_bubble",
    "smallcaps3",
    "fraktur2",
    "bold_fraktur",
    "bold_script",
    "handwriting1",
    "handwriting2",
    "rusify",
    "monospace",
    "dirty2",
    "knight2",
    "thin3",
    "tiny2",
    "upside_down1",
    "chinese_mafia",
    "sunday_cuddle",
    "native_lands",
    "foreign_friends",
    "atlantic",
    "funky_fresh",
    "greek_legends",
    "minion",
    "hippie",
    "sarah",
    "dwarf",
    "lilia",
    "smooth1",
    "smooth2",
    "carrier1",
    "carrier2",
    "awesome",
    "cjk",
    "cute1",
    "cute2",
    "cute3",
    "malayalam",
    "cranky",
    "lopioo",
    "scammer",
    "strikethrough",
    "drako",
    "celtic",
    "fasion",
    "curly",
    "russian",
    "russian2",
    "messletters",
    "coptic1",
    "swirly",
    "dotted",
    "coptic2",
    "parenthesized",
    "strange",
    "wiggly",
    "hazy",
    "hyves",
    "awcute",
    "slammer",
    "sheqi",
    "fari",
    "shasha",
    "pin1",
    "pin2",
    "sign",
    "bud1",
    "bud2",
    "old_italic",
    "ninja",
    "tai_viet",
    "subscript2",
    "fancy130",
    "smooth3",
    "flaky",
    "tiny_caps",
    "high_above",
    "handwriting3",
    "fantasy2",
    "manga",
    "upside_down2",
    "cool",
    "instagram",
    "tarty1",
    "tarty2",
    "tarty3",
    "tarty4",
    "tarty5",
    "tarty6",
    "tarty7",
    "tarty8",
    "tarty9",
    "got",
    "vip",
    "crazy",
    "cruse",
    "drippy",
    "stylish",
    "ayda"]

RANDOM_FILTERED_FONTS = [
    '5x8',
    'binary',
    'decimal',
    'high_noo',
    'hills',
    'katakana',
    'morse',
    'nfi1',
    'octal',
    'rot13',
    'smtengwar',
    'tengwar',
    'tsalagi',
    'gauntlet',
    'flyn_sh',
    'moscow',
    'dwhistled'] + NON_ASCII_FONTS

MIX_FILTERED_FONTS = [
    "tarty1",
    "tarty2",
    "tarty3",
    "tarty4",
    "tarty5",
    "tarty6",
    "tarty7",
    "tarty8",
    "tarty9"]

DESCRIPTION = '''ASCII art is also known as "computer text art".
It involves the smart placement of typed special characters or
letters to make a visual shape that is spread over multiple lines of text.
ART is a Python lib for text converting to ASCII art fancy.'''  # pragma: no cover


FONT_MAP = {"standard": [standard_dic, False]
            }
DECORATIONS_MAP = {"angry1": angry1,  # pragma: no cover
                   "arrow1": arrow1,
                   "arrow2": arrow2,
                   "arrow3": arrow3,
                   "arrow4": arrow4,
                   "arrow5": arrow5,
                   "arrow6": arrow6,
                   "arrow7": arrow7,
                   "arrow8": arrow8,
                   "arrow_wave1": arrow_wave1,
                   "arrow_wave2": arrow_wave2,
                   "ball1": ball1,
                   "ball2": ball2,
                   "ball3": ball3,
                   "barcode1": barcode1,
                   "bazar1": bazar1,
                   "block1": block1,
                   "block2": block2,
                   "bow1": bow1,
                   "bubble": bubble,
                   "cat1": cat1,
                   "cat2": cat2,
                   "cat3": cat3,
                   "cell1": cell1,
                   "champion1": champion1,
                   "chess1": chess1,
                   "confused1": confused1,
                   "confused2": confused2,
                   "cross1": cross1,
                   "depressed": depressed,
                   "diamon3": diamon3,
                   "diamond1": diamond1,
                   "diamond2": diamond2,
                   "egypt1": egypt1,
                   "emotions1": emotions1,
                   "fancy1": fancy1,
                   "fancy2": fancy2,
                   "fancy3": fancy3,
                   "fancy4": fancy4,
                   "fancy5": fancy5,
                   "fancy6": fancy6,
                   "fancy7": fancy7,
                   "fancy8": fancy8,
                   "fancy9": fancy9,
                   "fancy10": fancy10,
                   "fancy11": fancy11,
                   "fancy12": fancy12,
                   "fancy13": fancy13,
                   "fancy14": fancy14,
                   "fancy15": fancy15,
                   "fancy16": fancy16,
                   "fancy17": fancy17,
                   "fancy18": fancy18,
                   "fancy19": fancy19,
                   "fancy20": fancy20,
                   "fancy21": fancy21,
                   "fancy22": fancy22,
                   "fancy23": fancy23,
                   "fancy24": fancy24,
                   "fancy25": fancy25,
                   "fancy26": fancy26,
                   "fancy27": fancy27,
                   "fancy28": fancy28,
                   "fancy29": fancy29,
                   "fancy30": fancy30,
                   "fancy31": fancy31,
                   "fancy32": fancy32,
                   "fancy33": fancy33,
                   "fancy34": fancy34,
                   "fancy35": fancy35,
                   "fancy36": fancy36,
                   "fancy37": fancy37,
                   "fancy38": fancy38,
                   "fancy39": fancy39,
                   "fancy40": fancy40,
                   "fancy41": fancy41,
                   "fancy42": fancy42,
                   "fancy43": fancy43,
                   "fancy44": fancy44,
                   "fancy45": fancy45,
                   "fancy46": fancy46,
                   "fancy47": fancy47,
                   "fancy48": fancy48,
                   "fancy49": fancy49,
                   "fancy50": fancy50,
                   "fancy51": fancy51,
                   "fancy52": fancy52,
                   "fancy53": fancy53,
                   "fancy54": fancy54,
                   "fancy55": fancy55,
                   "fancy56": fancy56,
                   "fancy57": fancy57,
                   "fancy58": fancy58,
                   "fancy59": fancy59,
                   "fancy60": fancy60,
                   "fancy61": fancy61,
                   "fancy62": fancy62,
                   "fancy63": fancy63,
                   "fancy64": fancy64,
                   "fancy65": fancy65,
                   "fancy66": fancy66,
                   "fancy67": fancy67,
                   "fancy68": fancy68,
                   "fancy69": fancy69,
                   "fancy70": fancy70,
                   "fancy71": fancy71,
                   "fancy72": fancy72,
                   "fancy73": fancy73,
                   "fancy74": fancy74,
                   "fancy75": fancy75,
                   "fancy76": fancy76,
                   "fancy77": fancy77,
                   "fancy78": fancy78,
                   "fancy79": fancy79,
                   "fancy80": fancy80,
                   "fancy81": fancy81,
                   "fancy82": fancy82,
                   "fancy83": fancy83,
                   "fancy84": fancy84,
                   "fancy85": fancy85,
                   "fancy86": fancy86,
                   "fancy87": fancy87,
                   "fancy88": fancy88,
                   "fancy89": fancy89,
                   "fancy90": fancy90,
                   "fancy91": fancy91,
                   "fancy92": fancy92,
                   "fancy93": fancy93,
                   "fancy94": fancy94,
                   "fancy95": fancy95,
                   "flame1": flame1,
                   "flower1": flower1,
                   "food1": food1,
                   "food2": food2,
                   "haha": haha,
                   "happy1": happy1,
                   "happy_new_year": happy_new_year,
                   "hawaii1": hawaii1,
                   "hawaii2": hawaii2,
                   "heart1": heart1,
                   "heart2": heart2,
                   "heart3": heart3,
                   "heart4": heart4,
                   "heart5": heart5,
                   "heart6": heart6,
                   "heart7": heart7,
                   "heart8": heart8,
                   "heart9": heart9,
                   "heart10": heart10,
                   "heart11": heart11,
                   "heart12": heart12,
                   "heart13": heart13,
                   "heart14": heart14,
                   "heart15": heart15,
                   "line1": line1,
                   "line2": line2,
                   "line3": line3,
                   "line4": line4,
                   "love_music": love_music,
                   "lucky1": lucky1,
                   "missile1": missile1,
                   "mountain1": mountain1,
                   "mountain2": mountain2,
                   "mountain3": mountain3,
                   "music1": music1,
                   "music2": music2,
                   "music3": music3,
                   "pencil1": pencil1,
                   "poker1": poker1,
                   "puzzle1": puzzle1,
                   "puzzle2": puzzle2,
                   "puzzle3": puzzle3,
                   "sad1": sad1,
                   "sad2": sad2,
                   "sad3": sad3,
                   "sad4": sad4,
                   "smile1": smile1,
                   "snow1": snow1,
                   "snow2": snow2,
                   "soccer1": soccer1,
                   "star1": star1,
                   "star2": star2,
                   "star3": star3,
                   "star4": star4,
                   "star5": star5,
                   "star6": star6,
                   "star7": star7,
                   "star8": star8,
                   "star9": star9,
                   "star10": star10,
                   "star11": star11,
                   "star12": star12,
                   "star13": star13,
                   "star14": star14,
                   "star15": star15,
                   "star16": star16,
                   "star17": star17,
                   "star18": star18,
                   "star19": star19,
                   "star20": star20,
                   "star21": star21,
                   "star22": star22,
                   "star23": star23,
                   "star24": star24,
                   "star25": star25,
                   "temple1": temple1,
                   "title1": title1,
                   "tree1": tree1,
                   "wall1": wall1,
                   "wave1": wave1,
                   "wave2": wave2,
                   "wave3": wave3,
                   "wave4": wave4,
                   "wave5": wave5,
                   "wave6": wave6,
                   "wave7": wave7,
                   "wave8": wave8,
                   "wave9": wave9}

FONT_NAMES = sorted(list(FONT_MAP.keys()))  # pragma: no cover
ASCII_FONTS = sorted(set(FONT_NAMES) - set(NON_ASCII_FONTS))
DECORATION_NAMES = sorted(list(DECORATIONS_MAP.keys()))  # pragma: no cover
FONT_COUNTER = len(FONT_NAMES)  # pragma: no cover
DECORATION_COUNTER = len(DECORATION_NAMES)  # pragma: no cover
DEFAULT_FONT = "standard"  # pragma: no cover
